import type { NextPage } from "next";

import Head from "next/head";
import Image from "next/image";
import { useContext } from "react";
import Layout from "../Components/Layout/Layout";


const Home: NextPage = () => {
 
  return (
    <Layout>
      <div>
        <Head>
          <title>RaselKazi-Home</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/logo.png" />
        </Head>
      </div>

      <main className=" relative">
        <div className=" absolute hidden  dark:block -top-12   -right-52 h-32 w-5/6 bg-sky-600/20 rotate-45  blur-3xl "></div>

        <div className=" absolute hidden dark:block  bottom-12  -left-80 h-32 w-5/6  rotate-45  blur-3xl bg-sky-500/20 "></div>
        <div className=" absolute hidden dark:block  top-0 left-52 h-56 w-56 rounded-full  rotate-45  blur-3xl bg-gradient-to-r from-orange-500/20 via-purple-500/20 to-sky-500/30 "></div>
       
        
      </main>
    </Layout>
  );
};

export default Home;
